# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dicas Oracle
tagline:          - 
url:              http://tanakaa.github.io/oracle
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tanakaa/oracle